// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pswgsxyxhdhhpvugkdqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzd2dzeHl4aGRoaHB2dWdrZHFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMDU5MjUsImV4cCI6MjA1Nzc4MTkyNX0.IiJhneDLCqOqrDRnf6xarWnlGucKJ1qcY8Kh1WbGT6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);